apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
spec:
  containers:
    command:
    - /hyperkube
    - controller-manager
    - --master=127.0.0.1:8080
    - --cluster-cidr=100.64.0.0/10
    - --allocate-node-cidrs=true
    - --cloud-provider=gce
    - --service-account-private-key-file=/etc/kubernetes/apiserver-key.pem
    - --root-ca-file=/etc/kubernetes/ca.pem
    - --leader-elect=true
    - --logtostderr=true
    image: gcr.io/google_containers/kube-controller-manager:v1.3.0
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 1
    name: kube-controller-manager
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: etckube
      readOnly: true
    - mountPath: /etc/ssl
      name: etcssl
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: etckube
  - hostPath:
      path: /etc/ssl
    name: etcssl
