apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube:v1.5.3
    command:
    - /hyperkube
    - proxy
    - --master=KUBERNETES_MASTER_URL
    - --kubeconfig=/var/lib/kubelet/kubeconfig
    - --proxy-mode=iptables
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: etckube
      readOnly: true
    - mountPath: /etc/ssl/
      name: etcssl
      readOnly: true
    - mountPath: /var/lib/kubelet/
      name: kubeconfig
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: etckube
  - hostPath:
      path: /etc/ssl
    name: etcssl
  - hostPath:
      path: /var/lib/kubelet
    name: kubeconfig

